### ISSUE TITLE
页面没有加载过程

### ISSUE THREAD

**Issue by BelindaLiu** [MatchboxDorry/dorry-platform-frontend#101]
**Dorry UI Build Versin:**
Version:  0.1.12-alpha

**Operation System:**
Name: Ubuntu
Version: 16.04-LTS(64bit)

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.59 

**What I want to do**
打开任意页面

**Where I am**
首页

**What I have done**
点击左侧按钮

**What I expect:**
页面加载有过程

**What really happened**:
页面加载过程中一片空白

**Comment by dorry-terryli** [comment]
暂不修
