### ISSUE TITLE
remove all error service成功后页面不刷新

### ISSUE THREAD

**Issue by BelindaLiu** [MatchboxDorry/dorry-platform-frontend#106]
**Dorry UI Build Versin:**
Version:  0.1.12-alpha

**Operation System:**
Name: Ubuntu
Version: 16.04-LTS(64bit)

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.59 

**What I want to do**
remove all error service
**Where I am**
service页面

**What I have done**
点击remove all按钮

**What I expect:**
删除成功后，页面不显示error service

**What really happened**:
弹出成功提示后，页面没有变化

**Comment by BelindaLiu** [comment]
![screenshot from 2017-01-06 15-36-06](https://cloud.githubusercontent.com/assets/10137744/21710795/e8b56f88-d425-11e6-9825-d3c7e773879f.png)

**Comment by dorry-terryli** [comment]
x86没有遇到这种情况，arm上issue需调查
