### ISSUE TITLE
service页面Remove all 按钮不简洁

### ISSUE THREAD

**Issue by BelindaLiu** [MatchboxDorry/dorry-platform-frontend#107]
**Dorry UI Build Versin:**
Version:  0.1.12-alpha

**Operation System:**
Name: Ubuntu
Version: 16.04-LTS(64bit)

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.59 

**What I want to do**
remove all error service

**Where I am**
service页面

**What I have done**
查看remove all按钮

**What I expect:**
一个简单的清空图标

**What really happened**:
"remove all",　容易让人理解成删除所有service，也不够简洁明了。

**Comment by dorry-terryli** [comment]
已改为remove error
