### ISSUE TITLE
app start成功提示不全

### ISSUE THREAD

**Issue by BelindaLiu** [MatchboxDorry/dorry-platform-frontend#108]
**Dorry UI Build Versin:**
Version:  0.1.1４-alpha

**Operation System:**
Name: Ubuntu
Version: 16.04-LTS(64bit)

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.59 

**What I want to do**
start app

**Where I am**
app页面

**What I have done**
点击start按钮

**What I expect:**
启动成功

**What really happened**:
启动过程中，切换了页面，导致看不懂提示。
![screenshot from 2017-01-06 15-16-01](https://cloud.githubusercontent.com/assets/10137744/21710858/397d3bf8-d426-11e6-8388-980dbd2c1854.png)

**Comment by dorry-terryli** [comment]
修改为"start [image name] successfully" @BelindaLiu

**Comment by dorrywhale** [comment]
提示内容修改没问题。但是，当启动rpi-alpine-scratch时，提示成功，结果却是失败的，在 Stopped service 里看到了刚启动的。 @dorry-terryli

**Comment by dorry-terryli** [comment]
@dorrywhale 添加，start之后马上出错的runtime error
