### ISSUE TITLE
login页面不应该显示菜单栏

### ISSUE THREAD

**Issue by BelindaLiu** [MatchboxDorry/dorry-platform-frontend#109]
**Dorry UI Build Versin:**
Version:  0.1.1４-alpha

**Operation System:**
Name: Ubuntu
Version: 16.04-LTS(64bit)

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.59 

**What I want to do**
登录

**Where I am**
login页面

**What I have done**
查看页面

**What I expect:**
一个干净的登录页面

**What really happened**:
左边有菜单栏，右上角有登出按钮。
![screenshot from 2017-01-06 15-10-23](https://cloud.githubusercontent.com/assets/10137744/21710933/cc826a2c-d426-11e6-896a-a53ae26c69c3.png)

**Comment by Anna-92** [comment]
另，username和password没有图标，sign in按钮颜色跟我给出的设计不符

**Comment by Anna-92** [comment]
@dorry-terryli 输入用户名和密码后，看到输入框出现个黄色的背景。不需要这个背景。
另外，未输入任何数据直接点击log in,提示应该出现在log in按钮上方，而不是整个页面的右上角。

**Comment by dorry-terryli** [comment]
@Anna-92 黄色背景，是应为使用了自动补全选择用户名的方式，chrome给input 添加黄色背景，与编码无关．

**Comment by LiuBiHongHong** [comment]
@Anna-92 有新的问题可以提新的issue， 不用在别的issue的comments里面提
