### ISSUE TITLE
第一次打开市场，图片加载太慢

### ISSUE THREAD

**Issue by BelindaLiu** [MatchboxDorry/dorry-platform-frontend#111]
**Dorry UI Build Versin:**
Version:  0.1.1４-alpha

**Operation System:**
Name: Ubuntu
Version: 16.04-LTS(64bit)

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.59 

**What I want to do**
查看市场中app的介绍

**Where I am**
market页面

**What I have done**
查看页面

**What I expect:**
有简单介绍

**What really happened**:
2分钟后图标无法自动加载完成。
![screenshot from 2017-01-06 14-31-09](https://cloud.githubusercontent.com/assets/10137744/21711086/bb8ccb58-d427-11e6-8908-3043e37fbff9.png)

**Comment by dorry-terryli** [comment]
图片使用qiniu云服务
