### ISSUE TITLE
installing一个app时，切换到其他界面，然后再切换回Market界面，那个app恢复原样

### ISSUE THREAD

**Issue by Anna-92** [MatchboxDorry/dorry-platform-frontend#119]
**Dorry UI Build Versin:**
Version: 0.1.６-alpha

**Operation System:**
Name: Mac mini Os X EI Capitan
Version: 10.11.6

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.98 (64-bit)

**What I want to do**
我想安装一个app

**Where I am**
market页面

**What I have done**
点击一个app并Install，当它正在installing,我切换至其他页面，再切换至Market界面看那个app是否已经完成安装

**What I expect:**
那个app已成功安装

**What really happened**:
那个app还是老样子

**Comment by LiuBiHongHong** [comment]
暂不处理
