### ISSUE TITLE
Service界面里mouseover一个图标时，出现一个黑色边框

### ISSUE THREAD

**Issue by Anna-92** [MatchboxDorry/dorry-platform-frontend#120]
**Dorry UI Build Versin:**
Version: 0.1.15-alpha

**Operation System:**
Name: Mac mini Os X EI Capitan
Version: 10.11.6

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.98 (64-bit)

**What I want to do**
想点击一个图标进入详情

**Where I am**
service页面

**What I have done**
mouseover一个icon，进入详情页面

**What I expect:**
图标的mouseover状态是符合material design规范的

**What really happened**:
当mosueover一个图标时，出现了一个黑色的边框。

**Comment by Anna-92** [comment]
@dorry-terryli 请去掉黑色边框，加深mouseover时出现的阴影颜色

**Comment by dorry-terryli** [comment]
暂不修
