### ISSUE TITLE
Services的详情页面,状态栏下面的返回按钮和名字一排设计不美观

### ISSUE THREAD

**Issue by Anna-92** [MatchboxDorry/dorry-platform-frontend#121]
**Dorry UI Build Versin:**
Version: 0.1.15-alpha

**Operation System:**
Name: Mac mini Os X EI Capitan
Version: 10.11.6

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.98 (64-bit)

**What I want to do**
想进入service详情查看界面

**Where I am**
service页面

**What I have done**
点击一个图标进入详情页面查看

**What I expect:**
整体界面设计自然。

**What really happened**:
返回按钮和名字添加了白色背景，整体看起来不是很好看。

**Comment by dorry-terryli** [comment]
@Anna-92 issue title 与内容不符，请确认，对于issue title 中提到的，我认为service 详情也显示用户名及有logout 按钮没有问题，对于内容中service 返回按钮及名称放在第二排，[https://github.com/MatchboxDorry/dorry-web/issues/78](#78) 定位添加subtitle ．请确认

**Comment by Anna-92** [comment]
@dorry-terryli 去掉背景色，下方增加一条分割线，长度占据整个灰色页面，线条粗细、颜色参数参照该页面里的其他分割线。
