### ISSUE TITLE
app详情内，add和save的mouseover状态没有

### ISSUE THREAD

**Issue by Anna-92** [MatchboxDorry/dorry-platform-frontend#124]
**Dorry UI Build Versin:**
Version: 0.1.15-alpha

**Operation System:**
Name: Mac mini Os X EI Capitan
Version: 10.11.6

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.98 (64-bit)

**What I want to do**
想点击start进入详情查看界面

**Where I am**
app页面

**What I have done**
点击start按钮进入二级页面，查看edit my profile，点击了add和save

**What I expect:**
当鼠标分别移动至这两个按钮上时，呈现出mouseover状态

**What really happened**:
add和save按钮的mouseover状态没有

**Comment by dorry-terryli** [comment]
按start按钮的样式，按钮交互修改
