### ISSUE TITLE
启动相应服务后，Application页面应用中的 start 按钮应变为 stop 按钮

### ISSUE THREAD

**Issue by DawnTan-0321** [MatchboxDorry/dorry-platform-frontend#130]
**Dorry UI Build Version:**
Version:Alpha Release
（Market Version: 0.1.3
Frontend Version: latest
Backend Version: latest）

**Operation System:**
Name:Ubuntu
Version:16.04

**Browser:**
Browser name: Chrome
Browser version: 57.0.2987.133 (64-bit)

**What I want to do**

**Where I am**
Application 页面

**What I have done**
点击 Samba / Gitlab / WordPress / SnipeIT / Mediawiki 下绿色的 start 按钮
**What I expect:**
启动服务后，Application 页面中 Samba / Gitlab / WordPress / SnipeIT / Mediawiki 下 start 按钮变为可点击的 stop 按钮
**What really happened**:
Start 按钮没有变为 Stop 按钮

![dorry](https://cloud.githubusercontent.com/assets/26587863/24898325/1a8672c0-1ecf-11e7-917f-c0a764436621.png)

**Comment by liubihonghong** [comment]
与业务不符
@DawnTan-0321
