### ISSUE TITLE
想要app和service的个数统计

### ISSUE THREAD

**Issue by BelindaLiu** [MatchboxDorry/dorry-platform-frontend#37]
![Uploading Screenshot from 2016-10-28 11-40-18.png…]()
**Dorry UI Build Versin:**
Version: 0.1.2-alpha

**Operation System:**
Name: Ubuntu
Version: 16.04-LTS(64bit)

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.59 

**What I want to do**
我想要看到不同状态的service个数,以及已安装的app个数

**Where I am**
service页面和app页面

**What I have done**
查看

**What I expect:**
有统计信息

**What really happened**:
排满了各种图标，需要自己滚动页面去数
![screenshot from 2016-10-28 11-43-47](https://cloud.githubusercontent.com/assets/10137744/19798107/a70f997c-9d21-11e6-8c50-a1d11b6916a7.png)

**Comment by Anna-92** [comment]
app页面里，我会增加一个数量统计信息在工具栏下面
service页面里，我会分别在stopped service和running service右边增加个数统计信息
