### ISSUE TITLE
启动多个service，网站卡死

### ISSUE THREAD

**Issue by BelindaLiu** [MatchboxDorry/dorry-platform-frontend#47]
**Dorry UI Build Versin:**
Version: 0.1.2-alpha

**Operation System:**
Name: Ubuntu
Version: 16.04-LTS(64bit)

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.59 

**What I want to do**
想启动多个rpi-alphine服务

**Where I am**
app页面

**What I have done**
点击start，看到container started提示后，继续点击start，一共20次

**What I expect:**
增加20个running service

**What really happened**:
5～10秒内，service页面显示空白页。
接着回到app页面确认，经过5～10秒，app页面也显示空白页。
再次回到service页面，又经过10秒后，显示了十几个running service。

**Comment by dorry-terryli** [comment]
没有重现，需要QA启动多个alpine image
