### ISSUE TITLE
app没有应用的介绍

### ISSUE THREAD

**Issue by BelindaLiu** [MatchboxDorry/dorry-platform-frontend#69]
**Dorry UI Build Versin:**
Version:  0.2.0-hotfix-alpha

**Operation System:**
Name: Ubuntu
Version: 16.04-LTS(64bit)

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.59 

**What I want to do**
想查看app

**Where I am**
app页面

**What I have done**
查看页面

**What I expect:**
看到app的基本功能介绍

**What really happened**:
没有

**Comment by dorrywhale** [comment]
我会和 @Anna-92 明确设计

**Comment by dorry-terryli** [comment]
会修改页面，会将image info放入到二级页面当中
