### ISSUE TITLE
market无法取消app的安装

### ISSUE THREAD

**Issue by BelindaLiu** [MatchboxDorry/dorry-platform-frontend#86]
**Dorry UI Build Versin:**
Version:  0.2.0-hotfix-alpha

**Operation System:**
Name: Ubuntu
Version: 16.04-LTS(64bit)

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.59 

**What I want to do**
想取消安装app

**Where I am**
market页面

**What I have done**
点击install按钮后，想要取消操作

**What I expect:**
有取消按钮

**What really happened**:
没有可操作的按钮

**Comment by Anna-92** [comment]
@dorry-terryli 我会给出取消安装的设计。

**Comment by Anna-92** [comment]
BIJOL

**Comment by dorrywhale** [comment]
@anna-92, 这个是需要提交给我的issue

**Comment by dorrywhale** [comment]
暂时不做，作为下个release的需求。 @LiuBiHongHong
