### ISSUE TITLE
service详情出现空白项

### ISSUE THREAD

**Issue by BelindaLiu** [MatchboxDorry/dorry-platform-frontend#92]
**Dorry UI Build Versin:**
Version:  0.2.0-hotfix-alpha

**Operation System:**
Name: Ubuntu
Version: 16.04-LTS(64bit)

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.59 

**What I want to do**
想查看service信息

**Where I am**
service页面

**What I have done**
点击service图标进入详情

**What I expect:**
没有的项为none

**What really happened**:
空白项

![screenshot from 2016-12-09 12-05-57](https://cloud.githubusercontent.com/assets/10137744/21037356/2a14b918-be08-11e6-8174-3cfb5e7a833f.png)

**Comment by BelindaLiu** [comment]
问题依然存在。
![screenshot from 2016-12-23 14-59-56](https://cloud.githubusercontent.com/assets/10137744/21448711/8951dd5c-c920-11e6-8792-1d99773d046c.png)

**Comment by BelindaLiu** [comment]
V0.1.14-alpha fixed.

**Comment by BelindaLiu** [comment]
![screenshot from 2017-01-06 16-30-57](https://cloud.githubusercontent.com/assets/10137744/21712108/a7ece582-d42d-11e6-8ec8-8be4dc979785.png)

**Comment by BelindaLiu** [comment]
没修复

**Comment by dorry-terryli** [comment]
下周会解决
