### ISSUE TITLE
Market界面里的app没有显示app大小的数据

### ISSUE THREAD

**Issue by Anna-92** [MatchboxDorry/dorry-platform-frontend#96]
**Dorry UI Build Versin:**
Version: 0.1.６-alpha

**Operation System:**
Name: Mac mini Os X EI Capitan
Version: 10.11.6

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.98 (64-bit)

**What I want to do**
想看到market里的app的大小

**Where I am**
market页面

**What I have done**
点击菜单里的market进入market界面查看app的大小

**What I expect:**
想看到每个app的大小数据

**What really happened**:
每个app名字下方无显示其大小的数据

**Comment by dorry-terryli** [comment]
暂不修

**Comment by dorry-terryli** [comment]
docker registry api中获取不到image大小信息

**Comment by dorry-terryli** [comment]
@Anna-92 这个issue我们没有fix,请再仔细检查，不要添加fixed label
