### ISSUE TITLE
确认操作提示框里的按钮‘NO’存在感弱

### ISSUE THREAD

**Issue by Anna-92** [MatchboxDorry/dorry-platform-frontend#97]
**Dorry UI Build Versin:**
Version: 0.1.６-alpha

**Operation System:**
Name: Mac mini Os X EI Capitan
Version: 10.11.6

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.98 (64-bit)

**What I want to do**
想看确认操作的提示框视觉效果

**Where I am**
service页面

**What I have done**
随意点击任意一个按钮，看页面中间弹出的提示框

**What I expect:**
想看确认操作的提示框视觉效果

**What really happened**:
YES的默认按钮颜色不对，而‘NO’的文字颜色太淡

**Comment by dorry-terryli** [comment]
@Anna-92 需要给出按钮颜色

**Comment by dorrywhale** [comment]
Pass scenario, 如果大家对颜色有什么意见可以提。 @Anna-92 @dorry-terryli

**Comment by Anna-92** [comment]
之前的设计就很好（完全符合material design的设计规范），只是字体颜色调整一下即可。如需要，我会给出颜色。
